#!/bin/bash

RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

if ! [ -x "$(command -v ffmpeg)" ]; then
  echo -e "${RED}Please install ffmpeg and then run gifvid${NC}" >&2
  exit 1
fi

# default values
src=$1
crf=25

while [ "$1" != "" ]; do
  case $1 in
    -s | --src )  shift
                  src=$1
                  ;;
    -d | --dest ) shift
                  dest=$1
                  ;;
    -c | --crf ) shift
                 crf=$1
                 ;;
    esac
  shift
done

if [ -z $src ]; then
  echo -e "${RED}Please specify a source GIF${NC}" >&2
  exit 1
fi

if [ ! -f $src ]; then
  echo -e "${RED}File not found!${NC}" >&2
  exit 1
fi

if ! [ $dest ]; then
  dest="${src/gif/mp4}"
fi

ffmpeg -loglevel error -i $src -c:v libx264 -crf $crf -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -ac 2 -strict experimental -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -b:a 128k -movflags faststart $dest

if [ $? -eq 0 ]; then
  echo -e "Successfully converted $src to ${CYAN}$dest.${NC}" >&2
else
  echo -e "${RED}Conversion failed${NC}" >&2
fi
